#!/bin/bash
# restart named bluepill process group(s)
# - the list of groups is defined in smq_config/groups_$(hostname).yml

# change into parent (base) directory
BASE_DIR=`dirname $0`
cd $BASE_DIR/..

. bg/check_root

if [ -z "$1" ]; then
    echo "usage: restart_group [all|group_name[, group_name]]"
    echo e.g.
    echo "  restart_group bridge_bbc bridge_track"
    exit
fi

if [ "$1" = "all" ]; then
    groups=$(bg/get_groups)
else
    groups="$@"
fi

for group in $groups; do
    echo restarting [$group]
    bg/stop $group
    sleep 1
    bg/start $group
done
